node {
    stage('Checkout') {
        checkout(scm)
    }

    try{
        stage('Terraform init') {
            sh 'terraform init'
        }
        
        stage('Terraform apply') {
            sh 'terraform apply -auto-approve'
        }
    } catch (Throwable e) {
        throw e
    } finally {
        cleanWs()
    }
}
