node {
    stage('Checkout') {
        checkout(scm).each { k, v -> env.setProperty(k, v) }
        env.GIT_COMMIT_HASH = env.GIT_COMMIT.take(5)
    }

    try{
        stage('Terraform init') {
            sh 'terraform init'
        }
        
        stage('Terraform apply') {
            sh 'terraform apply -auto-approve'
        }
    } catch (Throwable e) {
        throw e
    } finally {
        cleanWs()
    }
}